export const collectionList = [
  {
    id: 1,
    name: 'Summer Sale',
    slug: 'summer-sale',
    isActive: true,
    productCount: 12,
    categoryCount: 3,
    createdAt: '2025-07-01',
  },
  {
    id: 2,
    name: 'New Arrival',
    slug: 'new-arrival',
    isActive: false,
    productCount: 8,
    categoryCount: 2,
    createdAt: '2025-06-21',
  },
  {
    id: 3,
    name: 'Best Sellers',
    slug: 'best-sellers',
    isActive: true,
    productCount: 20,
    categoryCount: 5,
    createdAt: '2025-07-28',
  },
  {
    id: 4,
    name: 'Best Sellers 1',
    slug: 'best-sellers-1',
    isActive: true,
    productCount: 20,
    categoryCount: 5,
    createdAt: '2025-07-28',
  },
  {
    id: 5,
    name: 'Best Sellers 2',
    slug: 'best-sellers-2',
    isActive: true,
    productCount: 20,
    categoryCount: 5,
    createdAt: '2025-07-28',
  },
]
